endpoints:
  - name: chat
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-4
      config:
        openai_api_type: "azure"
        openai_api_key: $OPENAI_API_KEY
        openai_deployment_name: "gpt-4"
        openai_api_base:  $AZURE_OPENAI_ENDPOINT
        openai_api_version: "2023-05-15"

  - name: completions
    endpoint_type: llm/v1/completions
    model:
      provider: openai
      name: gpt-4
      config:
        openai_api_type: "azure"
        openai_api_key: $AZURE_OPENAI_API_KEY
        openai_deployment_name: "gpt-4"
        openai_api_base: $AZURE_OPENAI_ENDPOINT
        openai_api_version: "2023-05-15"
        
  - name: embeddings
    endpoint_type: llm/v1/embeddings
    model:
      provider: openai
      name: text-embedding-ada-002
      config:
        openai_api_type: "azure"
        openai_api_key: $AZURE_OPENAI_API_KEY
        openai_deployment_name: "text-embedding-ada-002"
        openai_api_base: $AZURE_OPENAI_ENDPOINT
        openai_api_version: "2023-05-15"
